management:
  defaults:
    metrics:
      export:
        enabled: false
  simple:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health,metrics"

